### ISSUE TITLE
redpanda: can we help w/ the benches?

### ISSUE THREAD

**Issue by senior7515** [kmgowda/SBK#171]
hi all! very cool project. i came across this project and saw you added vectorizedio/redpanda which is great!

Let me know if we can help tune the bench or anything - i.e.: for prod we should run `rpk tune prod` (that's all really :) )

let me know

**Comment by kmgowda** [comment]
@senior7515 Thank you very much.. definitely , we may need your help for performance comparison between redpanda vs kafka and pravega on baremetal deployments.

But for now, let me know if there are any possible optimisations on SBK kafka/redpanda client (driver).
and i recommend please use the SBK and share the performance numbers from your side too.

**Comment by senior7515** [comment]
The setup for Redpanda is quite simple. The general guidance is 2G of ram per core. SSD and xfs file system should be the baseline we recommend. 

To tune the system is exactly one command (rpk tune prod) 

that’s is. There shouldn’t really be anything to do. That’s basically the premise the product. :)

i’ll give it a shot next weekend. If you run into issues I’m basically always online on our slack too (Vectorized.ioslack) - feel free to close the ticket. I just wanted to say very cool project!! :)

**Comment by kmgowda** [comment]
wow.. thank you very much for the appreciation .. its really very motivating to take the SBK to next possibilities .
