### ISSUE TITLE
Add a CSV logger 

### ISSUE THREAD

**Issue by TheCharmingSociopath** [kmgowda/SBK#204]
**Describe the Issue (Bug/Feature) **
I'll add a CSV logger to the project so that the results from SBK API can be easily parsed for post-processing. 

**Additional context**
Passing this SbkCSVLogger to SBK run would create a CSV file and dump the metrics there. That file can then be used for easy post-processing, instead of using the stdout dump.

**Comment by kmgowda** [comment]
thanks Aditiya.. please submit the PR with your code changes and test logs too.
