### ISSUE TITLE
Error when trying to get the performance benchmarking of MySQL 8.0.28 community edition on Windows 11

### ISSUE THREAD

**Issue by sushnag22** [kmgowda/SBK#316]
**Describe the Issue (Bug/Feature)**

Bug: When the example command `./build/install/sbk/bin/sbk -class mysql  -size 100 -writers 1 -seconds 60 `(as described in https://github.com/kmgowda/SBK/blob/master/driver-mysql/README.md) is executed in Git Bash in the root directory of this project or if the command  `./build/install/sbk/bin/sbk -class jdbc  -driver com.mysql.jdbc.Driver -url jdbc:mysql://localhost:3306/social -user root -password root  -table kmg_2 -size 100 -writers 1 -seconds 60`(as described in https://github.com/kmgowda/SBK/blob/master/driver-jdbc/README.md#jdbc-with-mysql) is executed in the root directory of this project, an error due to main class caused by ClassNotFoundException occurs.

**To Reproduce**

1. Run the command `./build/install/sbk/bin/sbk -class mysql  -size 100 -writers 1 -seconds 60 ` in the root directory of this project or run the command `./build/install/sbk/bin/sbk -class jdbc  -driver com.mysql.jdbc.Driver -url jdbc:mysql://localhost:3306/social -user root -password root  -table kmg_2 -size 100 -writers 1 -seconds 60` in the root directory of this project.
2. See error.

**Expected behavior**

The expected behavior is that the performance benchmarking results of MySQL should be displayed.

**Additional context**

1. The error says: 
`Error: Could not find or load main class io.sbk.main.SbkMain`
`Caused by: java.lang.ClassNotFoundException: io.sbk.main.SbkMain`

2. The same error occurs when running the command `./build/install/sbk-mysql/bin/sbk-mysql -class mysql  -size 100 -writers 1 -seconds 60 ` in the `driver-mysql` directory of this project or running the command `./build/install/sbk-jdbc/bin/sbk-jdbc -class jdbc  -driver com.mysql.jdbc.Driver -url jdbc:mysql://localhost:3306/social -user root -password root  -table kmg_2 -size 100 -writers 1 -seconds 60` in the `driver-jdbc` directory of this project.

3. My system information is attached below:

- OS Name: Microsoft Windows 11 Home Single Language
- Version: 10.0.22000 Build 22000

**Comment by kmgowda** [comment]
@sushnag22 This bug is not reproducible ; I am able to run file system benchmarking on windows 11

**Comment by kmgowda** [comment]
@sushnag22 see the results on windows 11: https://github.com/kmgowda/SBK/issues/316#issuecomment-1072441755

**Comment by sushnag22** [comment]
I'll recheck it and let you know sir.

**Comment by sushnag22** [comment]
Yes sir, It's working. I tried using command prompt and it's working fine, I'm not sure why it didn't work on the other day when I was using git bash.

![Screenshot](https://user-images.githubusercontent.com/74103829/159053950-4b8773d0-0e78-4a6f-bc9d-65b0daad0800.png)
