### ISSUE TITLE
Add Docker image for H2 database driver(driver-h2)

### ISSUE THREAD

**Issue by sushnag22** [kmgowda/SBK#347]
**Describe the Issue (Bug/Feature)**
Feature: Add Docker image for H2 database driver

**Additional context**
The Docker image for H2 database driver can be generated using the command: 
```
gradlew generateDockerfiles -Poutdir="docker-image/SBK/dockers"
``` 
Note: The above command runs on Windows and Linux, on MacOS use the command:
```
./gradlew generateDockerfiles -Poutdir="docker-image/SBK/dockers"
```
This command gives us the Docker file `sbk-h2` in the directory `driver-h2/docker-image/SBK/dockers`.

**Comment by shelar1423** [comment]
Can u reopen this @sushnag22
