### ISSUE TITLE
Add `-insecure` option to MinIO driver

### ISSUE THREAD

**Issue by thatsdone** [kmgowda/SBK#359]
**Describe the Issue (Bug/Feature)**

At the moment, driver-minio does not assume endpoints with self-signed certificates, and this causes exceptions when we try we try to https endpoints for these S3 compatible boxes.

**To Reproduce**

1. Prepare a S3 compatible object storage with a self-signed certificate.
2. Invoke SBK with `-class minio` and other workload specific parameters to the S3 compatible box.

**Expected behavior**

Disabling certificate validation and continue performance measurements.

Or, I think it's also worth considering adding '-cacert' option, but it should be another issue.

**Additional context**

**Note**
I already have a working patch. If this looks reasonable for the community, I can contribute it.

**Comment by kmgowda** [comment]
@thatsdone  Thank you very much for the issue .. please submit the patch , we will review code and eventually we will merge to the main also
