### ISSUE TITLE
import io.sbk.api.Parameters;

### ISSUE THREAD

**Issue by sanjaynv** [kmgowda/SBK#50]
import io.sbk.api.Parameters;
import org.apache.commons.configurations.ConfigurationException;
import org.apache.distributedlog.DistributedLogConfiguration;

I set all the required jar files and necessary libraries in their correct path, still 
Sir im finding an issue with this {Parameters, Commons, distributedlog} showing error message,

sir pls give a hint to resove this in your free time.

**Comment by kmgowda** [comment]
what is error that you are facing?

**Comment by kmgowda** [comment]
post the error log

**Comment by sanjaynv** [comment]
Sir it is in importing the necessary packages  [import io.sbk.api.*]
Intellij showing red color mark for      "Parameter", "Reader", "Writer", "commons" 

while building and run the project it gives "Error:(5, 27) java: class, interface, or enum expected"

I resolved the same issues for "io" and "sbk"  

please dont mind sir if im taking your precious time....

**Comment by kmgowda** [comment]
refer here on how to build: https://github.com/kmgowda/SBK#building
dont do the inteliji build and run

**Comment by sanjaynv** [comment]
K thank you sir

**Comment by sanjaynv** [comment]
Tq sir
